package com.example.demo.mail;

import com.example.demo.dto.UserDto;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;

public class EmailService {

    public EmailService(String to,Object obj) {

        // Put sender’s address
        String from = "b08545a2a4-2ae9a0@inbox.mailtrap.io";
        final String username = "4f90c3484d53ef";//username generated by Mailtrap
        final String password = "87434652e4b9b7";//password generated by Mailtrap

        // Paste host address from the SMTP settings tab in your Mailtrap Inbox
        String host = "smtp.mailtrap.io";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

        // Get the Session object.
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

        try {

            // Create a default MimeMessage object.
            Message message = new MimeMessage(session);
            // Set From: header field
            message.setFrom(new InternetAddress(from));
            // Set To: header field
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(to));
            // Set Subject: header field
            message.setSubject("New account confirmation");
            // Put the content of your message
            message.setText(prettyMail(obj));
            // Send message
            Transport.send(message);

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }

    private String prettyMail(Object obj) {
        UserDto userDto = (UserDto) obj;
        return "Dear " + userDto.getUsername()+ ", \n\n" +
                "We inform you that the account with next credentials was created:\nemail: "+
                userDto.getEmail()+"\npassword: "+userDto.getPassword()+
                "\n\n\nHave a great day!";

    }
}
